services:
  app:
    build:
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - "8000-8002:8000"
    volumes:
      - ./storage:/opt/app-root/src/storage
      - ./app:/opt/app-root/src/app
