version: "3.8"

services:
  app:
    build:
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - "8000-8002:8000"
    volumes:
      - ./storage:/opt/app-root/src/storage
      - ./app:/opt/app-root/src/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: supersecret
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass supersecret
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
