x-common:
  app-config: &app-config
    build:
      dockerfile: dev.Dockerfile
    tty: true
    volumes:
      - ./app:/opt/app-root/src/app

  common-env: &common-env
    REDIS_PORT: 6379
    REDIS_PASSWORD: supersecret
    RAFT_NODES: "app-1:8000,app-2:8000,app-3:8000"
    TZ: "Europe/Helsinki"

services:
  app-1:
    <<: *app-config
    ports:
      - "8000:8000"
    container_name: app-1
    environment:
      <<: *common-env
      REDIS_HOST: redis-1
      NODE_ID: 1
    depends_on:
      - redis-1

  redis-1:
    image: redis:latest
    command: redis-server --requirepass supersecret
    container_name: redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis-data-1:/data

  app-2:
    <<: *app-config
    ports:
      - "8001:8000"
    container_name: app-2
    environment:
      <<: *common-env
      REDIS_HOST: redis-2
      NODE_ID: 2
    depends_on:
      - redis-2

  redis-2:
    image: redis:latest
    command: redis-server --requirepass supersecret
    container_name: redis-2
    ports:
      - "6380:6379"
    volumes:
      - redis-data-2:/data

  app-3:
    <<: *app-config
    ports:
      - "8002:8000"
    container_name: app-3
    environment:
      <<: *common-env
      REDIS_HOST: redis-3
      NODE_ID: 3
    depends_on:
      - redis-3

  redis-3:
    image: redis:latest
    command: redis-server --requirepass supersecret
    container_name: redis-3
    ports:
      - "6381:6379"
    volumes:
      - redis-data-3:/data

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
