apiVersion: v1
kind: ConfigMap
metadata:
  name: distributed-filesystem-config
  labels:
    app: distributed-filesystem
data:
  RAFT_NODES: "distributed-filesystem-node-1:8080,distributed-filesystem-node-2:8080,distributed-filesystem-node-3:8080"
  NODE_1_ID: "1"
  NODE_1_REDIS_HOST: "redis-1"
  NODE_1_REDIS_PORT: "6379"
  NODE_1_REDIS_PASSWORD: "supersecret"
  NODE_2_ID: "2"
  NODE_2_REDIS_HOST: "redis-2"
  NODE_2_REDIS_PORT: "6379"
  NODE_2_REDIS_PASSWORD: "supersecret"
  NODE_3_ID: "3"
  NODE_3_REDIS_HOST: "redis-3"
  NODE_3_REDIS_PORT: "6379"
  NODE_3_REDIS_PASSWORD: "supersecret"
  TZ: "Europe/Helsinki"
