apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-filesystem
  labels:
      app: distributed-filesystem
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: distributed-filesystem
  template:
    metadata:
      labels:
        app: distributed-filesystem
    spec:
      containers:
        - name: distributed-filesystem
          image: ${{ secrets.OPENSHIFT_SERVER }}/ohtuprojekti-staging/distributed-filesystem-imagestream:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          volumeMounts:
            - name: file-volume
              mountPath: /opt/app-root/storage
      volumes:
        - name: file-volume 
          persistentVolumeClaim:
            claimName: file-bucket
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            from:
              kind: ImageStream
              name: distributed-filesystem-imagestream
---

