# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-bucket
  labels:
    app: file-bucket
spec:
  storageClassName: pomppa25-new
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

