apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-config-updater-binding
  namespace: ohtuprojekti-staging
subjects:
- kind: ServiceAccount
  name: default
  namespace: ohtuprojekti-staging
roleRef:
  kind: Role
  name: config-updater
  apiGroup: rbac.authorization.k8s.io
